# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        self.Windaw = QtWidgets.QWidget(MainWindow)
        self.Windaw.setObjectName("Windaw")
        
        # Create main layout
        mainLayout = QtWidgets.QVBoxLayout(self.Windaw)
        mainLayout.setSpacing(15)
        mainLayout.setContentsMargins(20, 20, 20, 20)
        
        self.Generator100watt = QtWidgets.QLabel(self.Windaw)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Generator100watt.setFont(font)
        self.Generator100watt.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Generator100watt.setObjectName("Generator100watt")
        self.Generator100watt.setAlignment(QtCore.Qt.AlignCenter)
        mainLayout.addWidget(self.Generator100watt)
        
        # Checkboxes layout
        checkboxLayout = QtWidgets.QVBoxLayout()
        checkboxLayout.setSpacing(10)
        
        self.UseNumba = QtWidgets.QCheckBox(self.Windaw)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UseNumba.setFont(font)
        self.UseNumba.setObjectName("UseNumba")
        checkboxLayout.addWidget(self.UseNumba)
        
        self.UseLeta = QtWidgets.QCheckBox(self.Windaw)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UseLeta.setFont(font)
        self.UseLeta.setObjectName("UseLeta")
        checkboxLayout.addWidget(self.UseLeta)
        
        mainLayout.addLayout(checkboxLayout)
        
        self.Resultiit = QtWidgets.QLabel(self.Windaw)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Resultiit.setFont(font)
        self.Resultiit.setObjectName("Resultiit")
        mainLayout.addWidget(self.Resultiit)
        
        mainLayout.addStretch()
        
        self.Degenerate = QtWidgets.QPushButton(self.Windaw)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Degenerate.setFont(font)
        self.Degenerate.setStyleSheet("background: rgb(255, 0, 255)")
        self.Degenerate.setObjectName("Degenerate")
        self.Degenerate.setMinimumHeight(35)
        mainLayout.addWidget(self.Degenerate)
        
        MainWindow.setCentralWidget(self.Windaw)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Generator100watt.setText(_translate("MainWindow", "Генератор паролів"))
        self.Resultiit.setText(_translate("MainWindow", "Тут буде результат"))
        self.UseNumba.setText(_translate("MainWindow", "Використовувати числа"))
        self.UseLeta.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.Degenerate.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
